### ISSUE TITLE
Got a traceback after updating to the latest version

### ISSUE THREAD

**Issue by John4650-hub** [thevickypedia/gmail-connector#5]
Hi, i don't know what has gone wrong but i got this log when ran my script. I hope you can look into it.
```terminal
Traceback (most recent call last):
  File "/home/runner/work/learn-java/learn-java/main.py", line [9](https://github.com/John4650-hub/learn-java/actions/runs/4149066754/jobs/7177685489#step:4:10), in <module>
    response = reader.instantiate(filters=(filter1, filter2, filter3))  # Apply multiple filters at the same time
  File "/home/runner/.local/lib/python3.[10](https://github.com/John4650-hub/learn-java/actions/runs/4149066754/jobs/7177685489#step:4:11)/site-packages/gmailconnector/read_email.py", line 98, in instantiate
    return_code, messages = self.mail.search(None, filters)
  File "/usr/lib/python3.10/imaplib.py", line 734, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib/python3.10/imaplib.py", line [12](https://github.com/John4650-hub/learn-java/actions/runs/4149066754/jobs/7177685489#step:4:13)30, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.10/imaplib.py", line 968, in _command
    raise self.error("command %s illegal in state %s, "
imaplib.IMAP4.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```

**Comment by thevickypedia** [comment]
@John4650-hub This means that any one of the filter passed is invalid. I see you're passing 3 filters. Can you post the values of it.

**Comment by John4650-hub** [comment]
These are the 3 
```python
filter1 = Condition.since(since=date(year=2023, month=2, day=11))
filter2 = Condition.subject(subject="Job-Logs-for-learn-java")
filter3 = Category.unseen
```
First i ran it with the last filter and got the same message.
Also i ran the script today.

**Comment by thevickypedia** [comment]
I fixed the bug in [v0.6.8](https://github.com/thevickypedia/gmail-connector/releases/tag/0.6.8)

**Comment by John4650-hub** [comment]
@thevickypedia  i am still getting the same Traceback
```terminal
Traceback (most recent call last):
  File "/home/runner/work/learn-java/learn-java/main.py", line [9](https://github.com/John4650-hub/learn-java/actions/runs/4152254739/jobs/7183087260#step:4:10), in <module>
    response = reader.instantiate(filters=(filter1, filter2, filter3))  # Apply multiple filters at the same time
  File "/home/runner/.local/lib/python3.[10](https://github.com/John4650-hub/learn-java/actions/runs/4152254739/jobs/7183087260#step:4:11)/site-packages/gmailconnector/read_email.py", line 91, in instantiate
    return_code, messages = self.mail.search(None, filters)
  File "/usr/lib/python3.10/imaplib.py", line 734, in search
    typ, dat = self._simple_command(name, *criteria)
  File "/usr/lib/python3.10/imaplib.py", line [12](https://github.com/John4650-hub/learn-java/actions/runs/4152254739/jobs/7183087260#step:4:13)30, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.10/imaplib.py", line 968, in _command
    raise self.error("command %s illegal in state %s, "
imaplib.IMAP4.error: command SEARCH illegal in state AUTH, only allowed in states SELECTED
```
Here is my script that reads the email

```python
from datetime import date

from gmailconnector import ReadEmail, Folder, Condition, Category

reader = ReadEmail(gmail_user='myemail@gmail.com',gmail_pass="myAppPassword",folder="important")  # Folder defaults to inbox
filter1 = Condition.since(since=date(year=2023, month=2, day=11))
filter2 = Condition.subject(subject="Job-Logs-for-learn-java")
filter3 = Category.unseen
response = reader.instantiate(filters=(filter1, filter2, filter3))  # Apply multiple filters at the same time
if response.ok:
    for each_mail in reader.read_mail(messages=response.body, humanize_datetime=False):  # False to get datetime object
        print(each_mail.date_time.date())
        print("[%s] %s" % (each_mail.sender_email, each_mail.sender))
        print("[%s] - %s" % (each_mail.subject, each_mail.body))
else:
    print(response.body)
```
Also i would like to know about the `.env`,  i created one file name `cred.env` and saved my credentials in it but got some error that meant that the credential were missing so now i just
pass them in the way they are.

**Comment by thevickypedia** [comment]
I'd like to call out three things
1. Make sure you're on the latest version. I'd suggest running
```shell
pip uninstall --no-cache-dir gmail-connector
pip install --no-cache --upgrade gmail-connector
pip freeze | grep gmail-connector
```
Verify if the output is `gmail-connector==0.6.8`

2. The folder you're passing should not be a string.
Change `folder="important"` to `folder=Folder.important`

3. To load the env variables automatically you should rename `cred.env` to just `.env`

Let me know how that goes.

**Comment by John4650-hub** [comment]
It was a success. Thanks.
